# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-16 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_icon_font_awesome', models.CharField(blank=True, max_length=48, null=True, verbose_name='Menu Icon Font Awesome')),
                ('menu_icon_image', models.ImageField(blank=True, null=True, upload_to='menu_icons/', verbose_name='Menu Icon Image')),
                ('menu_icon_url', models.URLField(blank=True, null=True, verbose_name='Menu Icon URL')),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.Page')),
                ('public_extension', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_extension', to='menu_icons.MenuIcon')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
